# ServiceAccount for the GMP frontend.
# The WI annotation binds it to the GSA created by Terraform (wif.yml: gmp-frontend)
# which has roles/monitoring.viewer, allowing the frontend to query Cloud Monitoring.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gmp-frontend
  namespace: gmp-public
  annotations:
    iam.gke.io/gcp-service-account: hippo-dev-cluster-gmp-frontend@project-ec2467ed-84cd-4898-b5b.iam.gserviceaccount.com
